DROP TABLE IF EXISTS test;
CREATE TABLE test (a int, b int);
INSERT INTO test VALUES (1, 1);
INSERT INTO test VALUES (2, 1);
INSERT INTO test VALUES (3, 1);
INSERT INTO test VALUES (4, 1);
INSERT INTO test VALUES (5, 1);
INSERT INTO test VALUES (1, 2);
INSERT INTO test VALUES (1, 2);
INSERT INTO test VALUES (1, 2);
INSERT INTO test VALUES (1, 2);
INSERT INTO test VALUES (1, 2);
SELECT * FROM test;

SELECT DISTINCT a, b FROM test;